# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v1.9.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import client
from client.rest import ApiException
from client.models.apps_v1beta1_deployment_condition import AppsV1beta1DeploymentCondition


class TestAppsV1beta1DeploymentCondition(unittest.TestCase):
    """ AppsV1beta1DeploymentCondition unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAppsV1beta1DeploymentCondition(self):
        """
        Test AppsV1beta1DeploymentCondition
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = client.models.apps_v1beta1_deployment_condition.AppsV1beta1DeploymentCondition()
        pass


if __name__ == '__main__':
    unittest.main()
